#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cmus
Version  : 2.10.0
Release  : 15
URL      : https://github.com/cmus/cmus/archive/v2.10.0/cmus-2.10.0.tar.gz
Source0  : https://github.com/cmus/cmus/archive/v2.10.0/cmus-2.10.0.tar.gz
Summary  : A small, fast and powerful console music player.
Group    : Development/Tools
License  : GPL-2.0
Requires: cmus-bin = %{version}-%{release}
Requires: cmus-data = %{version}-%{release}
Requires: cmus-filemap = %{version}-%{release}
Requires: cmus-lib = %{version}-%{release}
Requires: cmus-license = %{version}-%{release}
Requires: cmus-man = %{version}-%{release}
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(flac)
BuildRequires : pkgconfig(jack)
BuildRequires : pkgconfig(libavcodec)
BuildRequires : pkgconfig(libavformat)
BuildRequires : pkgconfig(libcdio)
BuildRequires : pkgconfig(libmodplug)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(opusfile)
BuildRequires : pkgconfig(samplerate)
BuildRequires : pkgconfig(vorbis)
BuildRequires : pkgconfig(wavpack)

%description
_cmus (originally _cmus_remote)
zsh completion for cmus-remote by Christian Schneider strcat AT gmx DOT net
extended for the main cmus binary by Frank Terbeck.

%package bin
Summary: bin components for the cmus package.
Group: Binaries
Requires: cmus-data = %{version}-%{release}
Requires: cmus-license = %{version}-%{release}
Requires: cmus-filemap = %{version}-%{release}

%description bin
bin components for the cmus package.


%package data
Summary: data components for the cmus package.
Group: Data

%description data
data components for the cmus package.


%package doc
Summary: doc components for the cmus package.
Group: Documentation
Requires: cmus-man = %{version}-%{release}

%description doc
doc components for the cmus package.


%package filemap
Summary: filemap components for the cmus package.
Group: Default

%description filemap
filemap components for the cmus package.


%package lib
Summary: lib components for the cmus package.
Group: Libraries
Requires: cmus-data = %{version}-%{release}
Requires: cmus-license = %{version}-%{release}
Requires: cmus-filemap = %{version}-%{release}

%description lib
lib components for the cmus package.


%package license
Summary: license components for the cmus package.
Group: Default

%description license
license components for the cmus package.


%package man
Summary: man components for the cmus package.
Group: Default

%description man
man components for the cmus package.


%prep
%setup -q -n cmus-2.10.0
cd %{_builddir}/cmus-2.10.0
pushd ..
cp -a cmus-2.10.0 buildavx2
popd
pushd ..
cp -a cmus-2.10.0 buildavx512
popd

%build
## build_prepend content
./configure prefix=/usr libdir=/usr/lib64
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1657114654
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
make  %{?_smp_mflags}

pushd ../buildavx2
## build_prepend content
./configure prefix=/usr libdir=/usr/lib64
## build_prepend end
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
make  %{?_smp_mflags}
popd
pushd ../buildavx512
## build_prepend content
./configure prefix=/usr libdir=/usr/lib64
## build_prepend end
export CFLAGS="$CFLAGS -m64 -march=x86-64-v4 -mprefer-vector-width=256 -Wl,-z,x86-64-v4"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v4 -mprefer-vector-width=256 -Wl,-z,x86-64-v4"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v4 -mprefer-vector-width=256 -Wl,-z,x86-64-v4"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v4 -mprefer-vector-width=256"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v4"
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1657114654
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cmus
cp %{_builddir}/cmus-2.10.0/COPYING %{buildroot}/usr/share/package-licenses/cmus/4cc77b90af91e615a64ae04893fdffa7939db84c
pushd ../buildavx2/
%make_install_v3
popd
pushd ../buildavx512/
%make_install_v4
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cmus
/usr/bin/cmus-remote
/usr/share/clear/optimized-elf/bin*

%files data
%defattr(-,root,root,-)
/usr/share/cmus/amazon.theme
/usr/share/cmus/cyan.theme
/usr/share/cmus/default.theme
/usr/share/cmus/dracula.theme
/usr/share/cmus/gray-88.theme
/usr/share/cmus/green-mono-88.theme
/usr/share/cmus/green.theme
/usr/share/cmus/gruvbox-alt.theme
/usr/share/cmus/gruvbox-warm.theme
/usr/share/cmus/gruvbox.theme
/usr/share/cmus/jellybeans.theme
/usr/share/cmus/night.theme
/usr/share/cmus/rc
/usr/share/cmus/solarized-dark.theme
/usr/share/cmus/solarized-light.theme
/usr/share/cmus/spotify.theme
/usr/share/cmus/xterm-white.theme
/usr/share/cmus/zenburn.theme

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/cmus/*

%files filemap
%defattr(-,root,root,-)
/usr/share/clear/filemap/filemap-cmus

%files lib
%defattr(-,root,root,-)
/usr/lib64/cmus/ip/cue.so
/usr/lib64/cmus/ip/ffmpeg.so
/usr/lib64/cmus/ip/flac.so
/usr/lib64/cmus/ip/modplug.so
/usr/lib64/cmus/ip/opus.so
/usr/lib64/cmus/ip/vorbis.so
/usr/lib64/cmus/ip/wav.so
/usr/lib64/cmus/ip/wavpack.so
/usr/lib64/cmus/op/alsa.so
/usr/lib64/cmus/op/jack.so
/usr/lib64/cmus/op/oss.so
/usr/lib64/cmus/op/pulse.so
/usr/share/clear/optimized-elf/other*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cmus/4cc77b90af91e615a64ae04893fdffa7939db84c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/cmus-remote.1
/usr/share/man/man1/cmus.1
/usr/share/man/man7/cmus-tutorial.7
